version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: nz_property_flip_db
    environment:
      POSTGRES_DB: nz_property_flip
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: nz_property_flip_backend
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/nz_property_flip
      FLASK_ENV: development
    ports:
      - "5000:5000"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./backend:/app
    command: python app.py

  frontend:
    build: ./frontend
    container_name: nz_property_flip_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev -- --host

volumes:
  postgres_data:

