import mimetypes
import os
import smtplib
from email.message import EmailMessage
from typing import List

from desktop.config import EmailConfig, DesktopConfig


def send_email(cfg: EmailConfig, subject: str, body: str, attachments: List[str]) -> None:
    if not cfg.enabled or not cfg.recipients:
        return

    msg = EmailMessage()
    msg["Subject"] = subject
    msg["From"] = cfg.username
    msg["To"] = ", ".join(cfg.recipients)
    msg.set_content(body)

    for path in attachments:
        if not os.path.exists(path):
            continue
        ctype, encoding = mimetypes.guess_type(path)
        if ctype is None or encoding is not None:
            ctype = "application/octet-stream"
        maintype, subtype = ctype.split("/", 1)
        with open(path, "rb") as f:
            msg.add_attachment(f.read(), maintype=maintype, subtype=subtype, filename=os.path.basename(path))

    with smtplib.SMTP(cfg.smtp_host, cfg.smtp_port) as server:
        server.starttls()
        if cfg.username and cfg.password:
            server.login(cfg.username, cfg.password)
        server.send_message(msg)


class EmailSender:
    """Email sender for desktop app."""
    
    def __init__(self, config: DesktopConfig):
        self.config = config
        
    def send_report_email(self, pdf_path: str, json_path: str = "") -> bool:
        """Send analysis report via email."""
        try:
            if not self.config.email.enabled or not self.config.email.recipients:
                print("Email not enabled or no recipients configured")
                return False
                
            # Prepare email content
            subject = f"RealFlip Analysis Report - {os.path.basename(pdf_path)}"
            body = f"""
RealFlip Analysis Report

This email contains the latest property analysis report.

Files attached:
- {os.path.basename(pdf_path)} (PDF Report)
{f"- {os.path.basename(json_path)} (Raw Data)" if json_path else ""}

Generated by RealFlip Desktop Batch Analyzer
            """.strip()
            
            # Prepare attachments
            attachments = [pdf_path]
            if json_path and os.path.exists(json_path):
                attachments.append(json_path)
            
            # Send email
            send_email(self.config.email, subject, body, attachments)
            print(f"Email sent to: {', '.join(self.config.email.recipients)}")
            return True
            
        except Exception as e:
            print(f"Email sending failed: {e}")
            return False


